In [1]:
import pandas as pd

In [33]:
offers = pd.read_csv("urls_5.csv")
offers

,id,cat,subcat,employment-typ,page,title,company,place,promo,date
0,5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb,information-technology-telecom,database-specialists-development,5,1,Chef des département de la centrale d'alarme 1...,Logjob AG - For Supply Chain Experts,Lausanne,True,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
1,0dda1844-754a-48f7-a75b-8dea041a5716,information-technology-telecom,database-specialists-development,5,1,Fachperson Gebäude- und Wohnungsregister (GWR)...,Baudirektion Kanton Zürich,Zürich,True,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
2,d353ebb9-1afa-403f-95dc-e0786788addc,information-technology-telecom,database-specialists-development,5,1,TypeScript Engineer,controlHome GmbH,Schönenberg ZH,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
3,0224a430-1d4c-4e61-979f-74ed8ef3bcad,information-technology-telecom,database-specialists-development,5,1,Data Management Expert (w/m/d),Migros-Genossenschafts-Bund,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
4,9c506732-af75-4e87-888f-2de5cb24dfc3,information-technology-telecom,database-specialists-development,5,1,Master Data Consultant,Valora Group,Muttenz,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
...,...,...,...,...,...,...,...,...,...,...
501,2f207304-e354-4944-84f2-6d78392d7805,information-technology-telecom,database-specialists-development,5,25,NEW: Big Data Engineer,Vicara Infotech Group AG,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
502,fa67ecc1-73b5-4b90-b955-00b69b840f75,information-technology-telecom,database-specialists-development,5,25,DWH EXPERT,Vicara Infotech Group AG,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
503,205fbc53-4102-4730-9e27-8b179e9977fd,information-technology-telecom,database-specialists-development,5,25,Datenbank-Entwickler/In,"IBV Informatik, Beratungs und Vertriebs AG",Bonstetten,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
504,f567bb77-b9a0-466d-bb67-1fb45a40f32f,information-technology-telecom,database-specialists-development,5,25,: Business Intelligence Entwickler 100% (w/m/d),Unterägeri,NaN,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
505,44231050-8362-4209-bc61-d516d33276b8,information-technology-telecom,database-specialists-development,5,25,Développeur de bases de données FileMaker,Lausanne,NaN,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."

In [34]:
offers.drop_duplicates(subset="id")

,id,cat,subcat,employment-typ,page,title,company,place,promo,date
0,5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb,information-technology-telecom,database-specialists-development,5,1,Chef des département de la centrale d'alarme 1...,Logjob AG - For Supply Chain Experts,Lausanne,True,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
1,0dda1844-754a-48f7-a75b-8dea041a5716,information-technology-telecom,database-specialists-development,5,1,Fachperson Gebäude- und Wohnungsregister (GWR)...,Baudirektion Kanton Zürich,Zürich,True,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
2,d353ebb9-1afa-403f-95dc-e0786788addc,information-technology-telecom,database-specialists-development,5,1,TypeScript Engineer,controlHome GmbH,Schönenberg ZH,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
3,0224a430-1d4c-4e61-979f-74ed8ef3bcad,information-technology-telecom,database-specialists-development,5,1,Data Management Expert (w/m/d),Migros-Genossenschafts-Bund,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
4,9c506732-af75-4e87-888f-2de5cb24dfc3,information-technology-telecom,database-specialists-development,5,1,Master Data Consultant,Valora Group,Muttenz,False,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
...,...,...,...,...,...,...,...,...,...,...
501,2f207304-e354-4944-84f2-6d78392d7805,information-technology-telecom,database-specialists-development,5,25,NEW: Big Data Engineer,Vicara Infotech Group AG,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
502,fa67ecc1-73b5-4b90-b955-00b69b840f75,information-technology-telecom,database-specialists-development,5,25,DWH EXPERT,Vicara Infotech Group AG,Zürich,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
503,205fbc53-4102-4730-9e27-8b179e9977fd,information-technology-telecom,database-specialists-development,5,25,Datenbank-Entwickler/In,"IBV Informatik, Beratungs und Vertriebs AG",Bonstetten,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
504,f567bb77-b9a0-466d-bb67-1fb45a40f32f,information-technology-telecom,database-specialists-development,5,25,: Business Intelligence Entwickler 100% (w/m/d),Unterägeri,NaN,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."
505,44231050-8362-4209-bc61-d516d33276b8,information-technology-telecom,database-specialists-development,5,25,Développeur de bases de données FileMaker,Lausanne,NaN,False,"(datetime.datetime(2022, 3, 31, 11, 24, 35, 24..."

In [35]:
offers["id"].value_counts().head(40)

74db9d88-1f9e-4da2-9d6e-eb96d4884af5    4
f4f0ce76-0334-45ee-b5b3-70fc42096a9c    3
40da8d2a-481f-4959-a83a-bba49f92bf87    3
69e7d134-ce01-477f-971a-483e9c2dc8e9    3
5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb    2
d3fba104-f81a-41f7-b902-994b3eda8fd3    2
5bff7567-db74-461a-8689-31ad5c2f79ac    2
7b088693-1933-40d8-b508-d5fc19d954ae    2
a8c828e2-0c34-4348-8876-96f80408c46e    2
0dda1844-754a-48f7-a75b-8dea041a5716    2
99a9f559-f7f5-43f9-8882-a382f68e5e8b    1
c76d7348-f403-4aa4-be63-e614897acf4e    1
d06fe225-ac7b-4d29-a86f-00eb4d027b76    1
fa3d9de6-6c54-4666-87a3-0d8af49522bc    1
afcc87e2-5158-432d-8f26-44e8a261679c    1
143e9f48-976e-44f7-a5c7-ffccda0e9e7a    1
f7310779-936d-4f6d-82b8-ac8fe07a7f06    1
7f22f51e-254c-469d-9d76-cfc0a9bf4d2b    1
9c573c52-60d8-4eb1-a1d9-5f272034f71b    1
aa1889d4-bbe9-4dd0-805d-b1ee36dfacb8    1
0b65fb12-70f6-44f7-abdf-c90184589a6b    1
005edf2d-b384-4868-8be0-c316b5348d2f    1
d339c514-0f2f-4610-a7ac-8b4b5426cee4    1
a1f9ab80-b1aa-4796-a562-00439bc51611    1
28e1f5c6-aabf-4f81-b06c-742337139c95    1
b3fc246e-35e5-4442-9df1-f71aecdd5086    1
e7ab9cac-e3b7-4cde-8040-e260158f784f    1
81d80c39-d006-4ff8-b12f-66b57079c83f    1
6ae61a05-7bc7-4bca-932a-71bee52b4a30    1
6a8b1bca-b333-4689-abde-eba22ec4a437    1
b7c6f069-6cdf-472c-90e3-4d6a36ef7c4f    1
a760eff6-0a31-46b2-ada5-260618507d6d    1
85be5ffb-6af0-44a7-bc54-4e0ab9b989b5    1
887afcca-08bc-4563-977b-7f157f5d635f    1
a29a8b71-a6dd-4388-b584-c002e262fd7f    1
a1513ed6-9763-4618-a866-1527f6dd17c6    1
948aa6ee-4036-405c-8b1a-ce4dc8edffba    1
3f2c36d1-1b51-4d42-aead-093c29e86e86    1
af047596-b847-4827-8c52-28aa9b71bdd0    1
26bece07-a2e1-4b3a-8d19-36d47af7be62    1
Name: id, dtype: int64

In [36]:
offers[offers["id"] == "5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb"]

,id,cat,subcat,employment-typ,page,title,company,place,promo,date
0,5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb,information-technology-telecom,database-specialists-development,5,1,Chef des département de la centrale d'alarme 1...,Logjob AG - For Supply Chain Experts,Lausanne,True,"(datetime.datetime(2022, 3, 31, 11, 24, 24, 19..."
68,5745af7a-1f9b-4ce4-96f1-2f0da8b0dffb,information-technology-telecom,database-specialists-development,5,3,Chef des département de la centrale d'alarme 1...,Logjob AG - For Supply Chain Experts,Lausanne,False,"(datetime.datetime(2022, 3, 31, 11, 24, 25, 13..."